/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GalleryResponseModel,
  NotFoundResult
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type galleriesResponse200 = {
  data: GalleryResponseModel[]
  status: 200
}

export type galleriesResponseSuccess = (galleriesResponse200) & {
  headers: Headers;
};
;

export type galleriesResponse = (galleriesResponseSuccess)

export const getGalleriesUrl = () => {




  return `${import.meta.env.VITE_API_URL}/api/Gallery`
}

export const galleries = async ( options?: RequestInit): Promise<galleriesResponse> => {

  const res = await fetch(getGalleriesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: galleriesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as galleriesResponse
}





export const getGalleriesQueryKey = () => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Gallery`
    ] as const;
    }


export const getGalleriesQueryOptions = <TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGalleriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof galleries>>> = ({ signal }) => galleries({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GalleriesQueryResult = NonNullable<Awaited<ReturnType<typeof galleries>>>
export type GalleriesQueryError = unknown


export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleries>>,
          TError,
          Awaited<ReturnType<typeof galleries>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleries>>,
          TError,
          Awaited<ReturnType<typeof galleries>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGalleriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type galleryByNameResponse200 = {
  data: GalleryResponseModel
  status: 200
}

export type galleryByNameResponse404 = {
  data: NotFoundResult
  status: 404
}

export type galleryByNameResponseSuccess = (galleryByNameResponse200) & {
  headers: Headers;
};
export type galleryByNameResponseError = (galleryByNameResponse404) & {
  headers: Headers;
};

export type galleryByNameResponse = (galleryByNameResponseSuccess | galleryByNameResponseError)

export const getGalleryByNameUrl = (name: string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Gallery/${name}`
}

export const galleryByName = async (name: string, options?: RequestInit): Promise<galleryByNameResponse> => {

  const res = await fetch(getGalleryByNameUrl(name),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: galleryByNameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as galleryByNameResponse
}





export const getGalleryByNameQueryKey = (name: string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Gallery/${name}`
    ] as const;
    }


export const getGalleryByNameQueryOptions = <TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGalleryByNameQueryKey(name);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof galleryByName>>> = ({ signal }) => galleryByName(name, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: name !== null && name !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GalleryByNameQueryResult = NonNullable<Awaited<ReturnType<typeof galleryByName>>>
export type GalleryByNameQueryError = NotFoundResult


export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleryByName>>,
          TError,
          Awaited<ReturnType<typeof galleryByName>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleryByName>>,
          TError,
          Awaited<ReturnType<typeof galleryByName>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGalleryByNameQueryOptions(name,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






