/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GalleryResponseModel,
  NotFoundResult
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGalleriesUrl = () => {




  return `${import.meta.env.VITE_API_URL}/api/Gallery`
}

export const galleries = async ( options?: Parameters<typeof customClient>[1]): Promise<GalleryResponseModel[]> => {

  return customClient<GalleryResponseModel[]>(getGalleriesUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGalleriesQueryKey = () => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Gallery`
    ] as const;
    }


export const getGalleriesQueryOptions = <TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGalleriesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof galleries>>> = ({ signal }) => galleries({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GalleriesQueryResult = NonNullable<Awaited<ReturnType<typeof galleries>>>
export type GalleriesQueryError = unknown


export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleries>>,
          TError,
          Awaited<ReturnType<typeof galleries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleries>>,
          TError,
          Awaited<ReturnType<typeof galleries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGalleries<TData = Awaited<ReturnType<typeof galleries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleries>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGalleriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGalleryByNameUrl = (name: string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Gallery/${name}`
}

export const galleryByName = async (name: string, options?: Parameters<typeof customClient>[1]): Promise<GalleryResponseModel> => {

  return customClient<GalleryResponseModel>(getGalleryByNameUrl(name),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGalleryByNameQueryKey = (name: string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Gallery/${name}`
    ] as const;
    }


export const getGalleryByNameQueryOptions = <TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGalleryByNameQueryKey(name);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof galleryByName>>> = ({ signal }) => galleryByName(name, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: name !== null && name !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GalleryByNameQueryResult = NonNullable<Awaited<ReturnType<typeof galleryByName>>>
export type GalleryByNameQueryError = NotFoundResult


export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleryByName>>,
          TError,
          Awaited<ReturnType<typeof galleryByName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof galleryByName>>,
          TError,
          Awaited<ReturnType<typeof galleryByName>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGalleryByName<TData = Awaited<ReturnType<typeof galleryByName>>, TError = NotFoundResult>(
 name: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof galleryByName>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGalleryByNameQueryOptions(name,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






