/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListTagsParams,
  ProblemDetails,
  SearchTagsParams,
  TagCreateRequestModel,
  TagCreateResponseModel,
  TagInfoResponseModelPagedData,
  TagSearchResponseModel
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type searchTagsResponse200 = {
  data: TagSearchResponseModel[]
  status: 200
}

export type searchTagsResponseSuccess = (searchTagsResponse200) & {
  headers: Headers;
};
;

export type searchTagsResponse = (searchTagsResponseSuccess)

export const getSearchTagsUrl = (params?: SearchTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/Tags/search?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/Tags/search`
}

export const searchTags = async (params?: SearchTagsParams, options?: RequestInit): Promise<searchTagsResponse> => {

  const res = await fetch(getSearchTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: searchTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as searchTagsResponse
}





export const getSearchTagsQueryKey = (params?: SearchTagsParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Tags/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchTagsQueryOptions = <TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchTagsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTags>>> = ({ signal }) => searchTags(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchTagsQueryResult = NonNullable<Awaited<ReturnType<typeof searchTags>>>
export type SearchTagsQueryError = unknown


export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params: undefined |  SearchTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchTagsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listTagsResponse200 = {
  data: TagInfoResponseModelPagedData
  status: 200
}

export type listTagsResponseSuccess = (listTagsResponse200) & {
  headers: Headers;
};
;

export type listTagsResponse = (listTagsResponseSuccess)

export const getListTagsUrl = (params?: ListTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/Tags/list?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/Tags/list`
}

export const listTags = async (params?: ListTagsParams, options?: RequestInit): Promise<listTagsResponse> => {

  const res = await fetch(getListTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listTagsResponse
}





export const getListTagsQueryKey = (params?: ListTagsParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Tags/list`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTagsQueryOptions = <TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTags>>> = ({ signal }) => listTags(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listTags>>>
export type ListTagsQueryError = unknown


export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params: undefined |  ListTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTagsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type tagCreateResponse201 = {
  data: TagCreateResponseModel
  status: 201
}

export type tagCreateResponse400 = {
  data: ProblemDetails
  status: 400
}

export type tagCreateResponseSuccess = (tagCreateResponse201) & {
  headers: Headers;
};
export type tagCreateResponseError = (tagCreateResponse400) & {
  headers: Headers;
};

export type tagCreateResponse = (tagCreateResponseSuccess | tagCreateResponseError)

export const getTagCreateUrl = () => {




  return `${import.meta.env.VITE_API_URL}/api/Tags`
}

export const tagCreate = async (tagCreateRequestModel?: TagCreateRequestModel, options?: RequestInit): Promise<tagCreateResponse> => {

  const res = await fetch(getTagCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tagCreateRequestModel)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: tagCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as tagCreateResponse
}





export const getTagCreateMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext> => {

const mutationKey = ['tagCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tagCreate>>, {data?: TagCreateRequestModel}> = (props) => {
          const {data} = props ?? {};

          return  tagCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TagCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tagCreate>>>
    export type TagCreateMutationBody = TagCreateRequestModel | undefined
    export type TagCreateMutationError = ProblemDetails

    export const useTagCreate = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tagCreate>>,
        TError,
        {data?: TagCreateRequestModel},
        TContext
      > => {
      return useMutation(getTagCreateMutationOptions(options), queryClient);
    }
