/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetApiTagsSearchParams,
  ListTagsParams,
  PagedDataOfTagInfoResponseModel,
  PagedDataOfTagSearchResponseModel
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getApiTagsSearchResponse200 = {
  data: PagedDataOfTagSearchResponseModel
  status: 200
}

export type getApiTagsSearchResponseSuccess = (getApiTagsSearchResponse200) & {
  headers: Headers;
};
;

export type getApiTagsSearchResponse = (getApiTagsSearchResponseSuccess)

export const getGetApiTagsSearchUrl = (params?: GetApiTagsSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://localhost:7043/api/Tags/search?${stringifiedParams}` : `https://localhost:7043/api/Tags/search`
}

export const getApiTagsSearch = async (params?: GetApiTagsSearchParams, options?: RequestInit): Promise<getApiTagsSearchResponse> => {

  const res = await fetch(getGetApiTagsSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getApiTagsSearchResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getApiTagsSearchResponse
}





export const getGetApiTagsSearchQueryKey = (params?: GetApiTagsSearchParams,) => {
    return [
    `https://localhost:7043/api/Tags/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetApiTagsSearchQueryOptions = <TData = Awaited<ReturnType<typeof getApiTagsSearch>>, TError = unknown>(params?: GetApiTagsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetApiTagsSearchQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getApiTagsSearch>>> = ({ signal }) => getApiTagsSearch(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetApiTagsSearchQueryResult = NonNullable<Awaited<ReturnType<typeof getApiTagsSearch>>>
export type GetApiTagsSearchQueryError = unknown


export function useGetApiTagsSearch<TData = Awaited<ReturnType<typeof getApiTagsSearch>>, TError = unknown>(
 params: undefined |  GetApiTagsSearchParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTagsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiTagsSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTagsSearch<TData = Awaited<ReturnType<typeof getApiTagsSearch>>, TError = unknown>(
 params?: GetApiTagsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getApiTagsSearch>>,
          TError,
          Awaited<ReturnType<typeof getApiTagsSearch>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetApiTagsSearch<TData = Awaited<ReturnType<typeof getApiTagsSearch>>, TError = unknown>(
 params?: GetApiTagsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetApiTagsSearch<TData = Awaited<ReturnType<typeof getApiTagsSearch>>, TError = unknown>(
 params?: GetApiTagsSearchParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getApiTagsSearch>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetApiTagsSearchQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listTagsResponse200 = {
  data: PagedDataOfTagInfoResponseModel
  status: 200
}

export type listTagsResponseSuccess = (listTagsResponse200) & {
  headers: Headers;
};
;

export type listTagsResponse = (listTagsResponseSuccess)

export const getListTagsUrl = (params?: ListTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://localhost:7043/api/Tags/list?${stringifiedParams}` : `https://localhost:7043/api/Tags/list`
}

export const listTags = async (params?: ListTagsParams, options?: RequestInit): Promise<listTagsResponse> => {

  const res = await fetch(getListTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listTagsResponse
}





export const getListTagsQueryKey = (params?: ListTagsParams,) => {
    return [
    `https://localhost:7043/api/Tags/list`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTagsQueryOptions = <TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTags>>> = ({ signal }) => listTags(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listTags>>>
export type ListTagsQueryError = unknown


export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params: undefined |  ListTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTagsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






