/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListTagsParams,
  ProblemDetails,
  SearchTagsParams,
  TagCreateRequestModel,
  TagCreateResponseModel,
  TagInfoResponseModelPagedData,
  TagSearchResponseModel
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getSearchTagsUrl = (params?: SearchTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/Tags/search?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/Tags/search`
}

export const searchTags = async (params?: SearchTagsParams, options?: Parameters<typeof customClient>[1]): Promise<TagSearchResponseModel[]> => {

  return customClient<TagSearchResponseModel[]>(getSearchTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getSearchTagsQueryKey = (params?: SearchTagsParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Tags/search`, ...(params ? [params] : [])
    ] as const;
    }


export const getSearchTagsQueryOptions = <TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSearchTagsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchTags>>> = ({ signal }) => searchTags(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SearchTagsQueryResult = NonNullable<Awaited<ReturnType<typeof searchTags>>>
export type SearchTagsQueryError = unknown


export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params: undefined |  SearchTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof searchTags>>,
          TError,
          Awaited<ReturnType<typeof searchTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSearchTags<TData = Awaited<ReturnType<typeof searchTags>>, TError = unknown>(
 params?: SearchTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof searchTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSearchTagsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListTagsUrl = (params?: ListTagsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/Tags/list?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/Tags/list`
}

export const listTags = async (params?: ListTagsParams, options?: Parameters<typeof customClient>[1]): Promise<TagInfoResponseModelPagedData> => {

  return customClient<TagInfoResponseModelPagedData>(getListTagsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListTagsQueryKey = (params?: ListTagsParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Tags/list`, ...(params ? [params] : [])
    ] as const;
    }


export const getListTagsQueryOptions = <TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTagsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTags>>> = ({ signal }) => listTags(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTagsQueryResult = NonNullable<Awaited<ReturnType<typeof listTags>>>
export type ListTagsQueryError = unknown


export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params: undefined |  ListTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTags>>,
          TError,
          Awaited<ReturnType<typeof listTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTags<TData = Awaited<ReturnType<typeof listTags>>, TError = unknown>(
 params?: ListTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTagsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getTagCreateUrl = () => {




  return `${import.meta.env.VITE_API_URL}/api/Tags`
}

export const tagCreate = async (tagCreateRequestModel?: TagCreateRequestModel, options?: Parameters<typeof customClient>[1]): Promise<TagCreateResponseModel> => {

  return customClient<TagCreateResponseModel>(getTagCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(tagCreateRequestModel)
  }
);}





export const getTagCreateMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext> => {

const mutationKey = ['tagCreate'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof tagCreate>>, {data?: TagCreateRequestModel}> = (props) => {
          const {data} = props ?? {};

          return  tagCreate(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type TagCreateMutationResult = NonNullable<Awaited<ReturnType<typeof tagCreate>>>
    export type TagCreateMutationBody = TagCreateRequestModel | undefined
    export type TagCreateMutationError = ProblemDetails

    export const useTagCreate = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof tagCreate>>, TError,{data?: TagCreateRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof tagCreate>>,
        TError,
        {data?: TagCreateRequestModel},
        TContext
      > => {
      return useMutation(getTagCreateMutationOptions(options), queryClient);
    }
