/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ListGroupParams,
  ListItemsParams,
  PagedDataOfDisplayItemResponseModel
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listItemsResponse200 = {
  data: PagedDataOfDisplayItemResponseModel
  status: 200
}

export type listItemsResponseSuccess = (listItemsResponse200) & {
  headers: Headers;
};
;

export type listItemsResponse = (listItemsResponseSuccess)

export const getListItemsUrl = (params?: ListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://localhost:7043/api/AssetBrowser?${stringifiedParams}` : `https://localhost:7043/api/AssetBrowser`
}

export const listItems = async (params?: ListItemsParams, options?: RequestInit): Promise<listItemsResponse> => {

  const res = await fetch(getListItemsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listItemsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listItemsResponse
}





export const getListItemsQueryKey = (params?: ListItemsParams,) => {
    return [
    `https://localhost:7043/api/AssetBrowser`, ...(params ? [params] : [])
    ] as const;
    }


export const getListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItems>>> = ({ signal }) => listItems(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listItems>>>
export type ListItemsQueryError = unknown


export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 params: undefined |  ListItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListItemsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listGroupResponse200 = {
  data: PagedDataOfDisplayItemResponseModel
  status: 200
}

export type listGroupResponseSuccess = (listGroupResponse200) & {
  headers: Headers;
};
;

export type listGroupResponse = (listGroupResponseSuccess)

export const getListGroupUrl = (groupId: number | string,
    params?: ListGroupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `https://localhost:7043/api/AssetBrowser/group/${groupId}?${stringifiedParams}` : `https://localhost:7043/api/AssetBrowser/group/${groupId}`
}

export const listGroup = async (groupId: number | string,
    params?: ListGroupParams, options?: RequestInit): Promise<listGroupResponse> => {

  const res = await fetch(getListGroupUrl(groupId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listGroupResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listGroupResponse
}





export const getListGroupQueryKey = (groupId: number | string,
    params?: ListGroupParams,) => {
    return [
    `https://localhost:7043/api/AssetBrowser/group/${groupId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getListGroupQueryOptions = <TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(groupId: number | string,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupQueryKey(groupId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroup>>> = ({ signal }) => listGroup(groupId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: groupId !== null && groupId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupQueryResult = NonNullable<Awaited<ReturnType<typeof listGroup>>>
export type ListGroupQueryError = unknown


export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number | string,
    params: undefined |  ListGroupParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroup>>,
          TError,
          Awaited<ReturnType<typeof listGroup>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number | string,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroup>>,
          TError,
          Awaited<ReturnType<typeof listGroup>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number | string,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number | string,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupQueryOptions(groupId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






