/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DisplayItemResponseModelPagedData,
  ListGroupParams,
  ListItemsParams
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListItemsUrl = (gallery: string,
    params?: ListItemsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    const explodeParameters = ["Tags","ExcludeTags"];

    if (Array.isArray(value) && explodeParameters.includes(key)) {
      value.forEach((v) => {
        normalizedParams.append(key, v === null ? 'null' : String(v));
      });
      return;
    }

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/AssetBrowser/${gallery}?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/AssetBrowser/${gallery}`
}

export const listItems = async (gallery: string,
    params?: ListItemsParams, options?: Parameters<typeof customClient>[1]): Promise<DisplayItemResponseModelPagedData> => {

  return customClient<DisplayItemResponseModelPagedData>(getListItemsUrl(gallery,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListItemsQueryKey = (gallery: string,
    params?: ListItemsParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/AssetBrowser/${gallery}`, ...(params ? [params] : [])
    ] as const;
    }


export const getListItemsQueryOptions = <TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(gallery: string,
    params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListItemsQueryKey(gallery,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listItems>>> = ({ signal }) => listItems(gallery,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: gallery !== null && gallery !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListItemsQueryResult = NonNullable<Awaited<ReturnType<typeof listItems>>>
export type ListItemsQueryError = unknown


export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 gallery: string,
    params: undefined |  ListItemsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 gallery: string,
    params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listItems>>,
          TError,
          Awaited<ReturnType<typeof listItems>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 gallery: string,
    params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListItems<TData = Awaited<ReturnType<typeof listItems>>, TError = unknown>(
 gallery: string,
    params?: ListItemsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listItems>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListItemsQueryOptions(gallery,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getListGroupUrl = (groupId: number,
    params?: ListGroupParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${import.meta.env.VITE_API_URL}/api/AssetBrowser/group/${groupId}?${stringifiedParams}` : `${import.meta.env.VITE_API_URL}/api/AssetBrowser/group/${groupId}`
}

export const listGroup = async (groupId: number,
    params?: ListGroupParams, options?: Parameters<typeof customClient>[1]): Promise<DisplayItemResponseModelPagedData> => {

  return customClient<DisplayItemResponseModelPagedData>(getListGroupUrl(groupId,params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getListGroupQueryKey = (groupId: number,
    params?: ListGroupParams,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/AssetBrowser/group/${groupId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getListGroupQueryOptions = <TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(groupId: number,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListGroupQueryKey(groupId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listGroup>>> = ({ signal }) => listGroup(groupId,params, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: groupId !== null && groupId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListGroupQueryResult = NonNullable<Awaited<ReturnType<typeof listGroup>>>
export type ListGroupQueryError = unknown


export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number,
    params: undefined |  ListGroupParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroup>>,
          TError,
          Awaited<ReturnType<typeof listGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listGroup>>,
          TError,
          Awaited<ReturnType<typeof listGroup>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListGroup<TData = Awaited<ReturnType<typeof listGroup>>, TError = unknown>(
 groupId: number,
    params?: ListGroupParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listGroup>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListGroupQueryOptions(groupId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






