/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */

export interface AssetGroupPositionResponseModel {
  assetId: number;
  isInGroup: boolean;
  /** @nullable */
  groupId?: number | null;
  /** @nullable */
  nextAsset?: number | null;
  /** @nullable */
  previousAsset?: number | null;
}
