/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import type { TagDtoInfo } from './tagDtoInfo';

export type AssetTagsResponseModelTags = {[key: string]: TagDtoInfo[]};
