/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { TagDtoInfo } from './tagDtoInfo';

/**
 * @nullable
 */
export type AssetTagsResponseModelTags = {[key: string]: TagDtoInfo[]} | null;
