/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { AssetPosition } from './assetPosition';

export interface AssetGroupResponseModel {
  id: number;
  galleryId: number;
  coverAssetPosition: number;
  isEditable: boolean;
  assetsCount: number;
  /** @nullable */
  positions: AssetPosition[] | null;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  physicalPath?: string | null;
}
