/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { DisplayItemType } from './displayItemType';

export interface DisplayItemResponseModel {
  type: DisplayItemType;
  id: number;
  creationTime: string;
  importTime: string;
  /** @nullable */
  title?: string | null;
  /** @nullable */
  count?: number | null;
}
