/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export type DisplayItemType = typeof DisplayItemType[keyof typeof DisplayItemType];


export const DisplayItemType = {
  Asset: 'Asset',
  Group: 'Group',
} as const;
