/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { DisplayItemResponseModel } from './displayItemResponseModel';

export interface DisplayItemResponseModelPagedData {
  items: DisplayItemResponseModel[];
  skip: number;
  take: number;
  totalCount: number;
  pagesCount: number;
}
