/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DisplayItemType } from './displayItemType';

export interface DisplayItemResponseModel {
  type: DisplayItemType;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  creationTime: string;
  importTime: string;
  /** @nullable */
  title?: string | null;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  count?: number | string | null;
}
