/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import type { StringSegment } from './stringSegment';

export interface EntityTagHeaderValue {
  tag?: StringSegment;
  isWeak?: boolean;
}
