/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import type { EntityTagHeaderValue } from './entityTagHeaderValue';
import type { Stream } from './stream';

export interface FileStreamResult {
  fileStream?: Stream;
  /** @nullable */
  contentType?: string | null;
  /** @nullable */
  fileDownloadName?: string | null;
  /** @nullable */
  lastModified?: string | null;
  entityTag?: null | EntityTagHeaderValue;
  enableRangeProcessing?: boolean;
}
