/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export interface GalleryResponseModel {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id: number | string;
  name: string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  coverAssetId: number | string | null;
}
