/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */

export interface GalleryResponseModel {
  id: number;
  name: string;
  /** @nullable */
  coverAssetId?: number | null;
}
