/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export type GetApiTagsSearchParams = {
value?: string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
take?: number | string;
};
