/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */

export type ListItemsParams = {
Tags?: string[];
ExcludeTags?: string[];
Skip?: number;
Take?: number;
};
