/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export type ListItemsParams = {
Tags?: string[];
ExcludeTags?: string[];
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Skip?: number | string;
/**
 * @pattern ^-?(?:0|[1-9]\d*)$
 */
Take?: number | string;
};
