/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import type { DisplayItemResponseModel } from './displayItemResponseModel';

export interface PagedDataOfDisplayItemResponseModel {
  items: DisplayItemResponseModel[];
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  skip: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  take: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  totalCount: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  pagesCount?: number | string;
}
