/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { AssetPosition } from './assetPosition';

export interface SetAssetPositionsRequestModel {
  positions: AssetPosition[];
}
