/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export interface StringSegment {
  /** @nullable */
  buffer?: string | null;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  offset?: number | string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  length?: number | string;
  /** @nullable */
  value?: string | null;
  hasValue?: boolean;
}
