/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TagDto {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  categoryId?: number | string;
  /**
     * @nullable
     * @pattern ^-?(?:0|[1-9]\d*)$
     */
  canonicalId?: number | string | null;
  isCanonocal?: boolean;
}
