/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */

export interface TagDtoInfo {
  id: number;
  name: string;
  category: string;
  occurrences: number;
  /** @nullable */
  canonicalId?: number | null;
  /** @nullable */
  canonicalName?: string | null;
  readonly isCanonical: boolean;
}
