/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { TagInfoResponseModel } from './tagInfoResponseModel';

export interface TagInfoResponseModelPagedData {
  /** @nullable */
  items: TagInfoResponseModel[] | null;
  skip: number;
  take: number;
  totalCount: number;
  pagesCount: number;
}
