/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import type { TagInfoResponseModel } from './tagInfoResponseModel';

export interface TagInfoResponseModelPagedData {
  items: TagInfoResponseModel[];
  skip: number;
  take: number;
  totalCount: number;
  pagesCount: number;
}
