/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */

export interface TagSearchResponseModel {
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  id?: number | string;
  name?: string;
  category?: string;
  /** @pattern ^-?(?:0|[1-9]\d*)$ */
  occurrences?: number | string;
  isCanonical?: boolean;
  /** @nullable */
  canonicalName?: string | null;
}
