/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */

export interface TagSearchResponseModel {
  id: number;
  /** @minLength 1 */
  name: string;
  /** @minLength 1 */
  category: string;
  occurrences: number;
  isCanonical: boolean;
  /** @nullable */
  canonicalName?: string | null;
}
