/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type assetResponse200 = {
  data: Blob
  status: 200
}

export type assetResponseSuccess = (assetResponse200) & {
  headers: Headers;
};
;

export type assetResponse = (assetResponseSuccess)

export const getAssetUrl = (id: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/${id}`
}

export const asset = async (id: number | string, options?: RequestInit): Promise<assetResponse> => {

  const res = await fetch(getAssetUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: assetResponse['data'] = body as assetResponse['data']
  return { data, status: res.status, headers: res.headers } as assetResponse
}





export const getAssetQueryKey = (id: number | string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/${id}`
    ] as const;
    }


export const getAssetQueryOptions = <TData = Awaited<ReturnType<typeof asset>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof asset>>> = ({ signal }) => asset(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetQueryResult = NonNullable<Awaited<ReturnType<typeof asset>>>
export type AssetQueryError = unknown


export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof asset>>,
          TError,
          Awaited<ReturnType<typeof asset>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof asset>>,
          TError,
          Awaited<ReturnType<typeof asset>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type assetPreviewResponse200 = {
  data: Blob
  status: 200
}

export type assetPreviewResponseSuccess = (assetPreviewResponse200) & {
  headers: Headers;
};
;

export type assetPreviewResponse = (assetPreviewResponseSuccess)

export const getAssetPreviewUrl = (id: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/asset/preview/${id}`
}

export const assetPreview = async (id: number | string, options?: RequestInit): Promise<assetPreviewResponse> => {

  const res = await fetch(getAssetPreviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: assetPreviewResponse['data'] = body as assetPreviewResponse['data']
  return { data, status: res.status, headers: res.headers } as assetPreviewResponse
}





export const getAssetPreviewQueryKey = (id: number | string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/asset/preview/${id}`
    ] as const;
    }


export const getAssetPreviewQueryOptions = <TData = Awaited<ReturnType<typeof assetPreview>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetPreviewQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetPreview>>> = ({ signal }) => assetPreview(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof assetPreview>>>
export type AssetPreviewQueryError = unknown


export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetPreview>>,
          TError,
          Awaited<ReturnType<typeof assetPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetPreview>>,
          TError,
          Awaited<ReturnType<typeof assetPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetPreviewQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type groupPreviewResponse200 = {
  data: Blob
  status: 200
}

export type groupPreviewResponseSuccess = (groupPreviewResponse200) & {
  headers: Headers;
};
;

export type groupPreviewResponse = (groupPreviewResponseSuccess)

export const getGroupPreviewUrl = (id: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/group/preview/${id}`
}

export const groupPreview = async (id: number | string, options?: RequestInit): Promise<groupPreviewResponse> => {

  const res = await fetch(getGroupPreviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: groupPreviewResponse['data'] = body as groupPreviewResponse['data']
  return { data, status: res.status, headers: res.headers } as groupPreviewResponse
}





export const getGroupPreviewQueryKey = (id: number | string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/group/preview/${id}`
    ] as const;
    }


export const getGroupPreviewQueryOptions = <TData = Awaited<ReturnType<typeof groupPreview>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGroupPreviewQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof groupPreview>>> = ({ signal }) => groupPreview(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GroupPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof groupPreview>>>
export type GroupPreviewQueryError = unknown


export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupPreview>>,
          TError,
          Awaited<ReturnType<typeof groupPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupPreview>>,
          TError,
          Awaited<ReturnType<typeof groupPreview>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGroupPreviewQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type assetMimeTypeResponse200 = {
  data: string
  status: 200
}

export type assetMimeTypeResponseSuccess = (assetMimeTypeResponse200) & {
  headers: Headers;
};
;

export type assetMimeTypeResponse = (assetMimeTypeResponseSuccess)

export const getAssetMimeTypeUrl = (id: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/asset/${id}/mime-type`
}

export const assetMimeType = async (id: number | string, options?: RequestInit): Promise<assetMimeTypeResponse> => {

  const res = await fetch(getAssetMimeTypeUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assetMimeTypeResponse['data'] = body !== null ? body : ''
  return { data, status: res.status, headers: res.headers } as assetMimeTypeResponse
}





export const getAssetMimeTypeQueryKey = (id: number | string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/asset/${id}/mime-type`
    ] as const;
    }


export const getAssetMimeTypeQueryOptions = <TData = Awaited<ReturnType<typeof assetMimeType>>, TError = unknown>(id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetMimeTypeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetMimeType>>> = ({ signal }) => assetMimeType(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetMimeTypeQueryResult = NonNullable<Awaited<ReturnType<typeof assetMimeType>>>
export type AssetMimeTypeQueryError = unknown


export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = unknown>(
 id: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetMimeType>>,
          TError,
          Awaited<ReturnType<typeof assetMimeType>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetMimeType>>,
          TError,
          Awaited<ReturnType<typeof assetMimeType>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = unknown>(
 id: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetMimeTypeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






