/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProblemDetails
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAssetUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/${id}`
}

export const asset = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<Blob> => {

  return customClient<Blob>(getAssetUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAssetQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/${id}`
    ] as const;
    }


export const getAssetQueryOptions = <TData = Awaited<ReturnType<typeof asset>>, TError = Blob>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof asset>>> = ({ signal }) => asset(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetQueryResult = NonNullable<Awaited<ReturnType<typeof asset>>>
export type AssetQueryError = Blob


export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = Blob>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof asset>>,
          TError,
          Awaited<ReturnType<typeof asset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof asset>>,
          TError,
          Awaited<ReturnType<typeof asset>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAsset<TData = Awaited<ReturnType<typeof asset>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof asset>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getAssetPreviewUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/asset/preview/${id}`
}

export const assetPreview = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<Blob> => {

  return customClient<Blob>(getAssetPreviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAssetPreviewQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/asset/preview/${id}`
    ] as const;
    }


export const getAssetPreviewQueryOptions = <TData = Awaited<ReturnType<typeof assetPreview>>, TError = Blob>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetPreviewQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetPreview>>> = ({ signal }) => assetPreview(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof assetPreview>>>
export type AssetPreviewQueryError = Blob


export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = Blob>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetPreview>>,
          TError,
          Awaited<ReturnType<typeof assetPreview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetPreview>>,
          TError,
          Awaited<ReturnType<typeof assetPreview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetPreview<TData = Awaited<ReturnType<typeof assetPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetPreviewQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGroupPreviewUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/group/preview/${id}`
}

export const groupPreview = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<Blob> => {

  return customClient<Blob>(getGroupPreviewUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGroupPreviewQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/group/preview/${id}`
    ] as const;
    }


export const getGroupPreviewQueryOptions = <TData = Awaited<ReturnType<typeof groupPreview>>, TError = Blob>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGroupPreviewQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof groupPreview>>> = ({ signal }) => groupPreview(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GroupPreviewQueryResult = NonNullable<Awaited<ReturnType<typeof groupPreview>>>
export type GroupPreviewQueryError = Blob


export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = Blob>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupPreview>>,
          TError,
          Awaited<ReturnType<typeof groupPreview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupPreview>>,
          TError,
          Awaited<ReturnType<typeof groupPreview>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGroupPreview<TData = Awaited<ReturnType<typeof groupPreview>>, TError = Blob>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupPreview>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGroupPreviewQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getAssetMimeTypeUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Media/asset/${id}/mime-type`
}

export const assetMimeType = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<string> => {

  return customClient<string>(getAssetMimeTypeUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAssetMimeTypeQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Media/asset/${id}/mime-type`
    ] as const;
    }


export const getAssetMimeTypeQueryOptions = <TData = Awaited<ReturnType<typeof assetMimeType>>, TError = ProblemDetails>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetMimeTypeQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetMimeType>>> = ({ signal }) => assetMimeType(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetMimeTypeQueryResult = NonNullable<Awaited<ReturnType<typeof assetMimeType>>>
export type AssetMimeTypeQueryError = ProblemDetails


export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = ProblemDetails>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetMimeType>>,
          TError,
          Awaited<ReturnType<typeof assetMimeType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetMimeType>>,
          TError,
          Awaited<ReturnType<typeof assetMimeType>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetMimeType<TData = Awaited<ReturnType<typeof assetMimeType>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetMimeType>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetMimeTypeQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






