/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssetGroupResponseModel,
  ProblemDetails,
  SetAssetPositionsRequestModel,
  SetGroupCoverRequestModel
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGroupDetailsUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Groups/${id}`
}

export const groupDetails = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<AssetGroupResponseModel> => {

  return customClient<AssetGroupResponseModel>(getGroupDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGroupDetailsQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Groups/${id}`
    ] as const;
    }


export const getGroupDetailsQueryOptions = <TData = Awaited<ReturnType<typeof groupDetails>>, TError = ProblemDetails>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGroupDetailsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof groupDetails>>> = ({ signal }) => groupDetails(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GroupDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof groupDetails>>>
export type GroupDetailsQueryError = ProblemDetails


export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = ProblemDetails>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupDetails>>,
          TError,
          Awaited<ReturnType<typeof groupDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupDetails>>,
          TError,
          Awaited<ReturnType<typeof groupDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = ProblemDetails>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGroupDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getGroupSetPositonsUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Groups/${id}/positions`
}

export const groupSetPositons = async (id: number,
    setAssetPositionsRequestModel?: SetAssetPositionsRequestModel, options?: Parameters<typeof customClient>[1]): Promise<void> => {

  return customClient<void>(getGroupSetPositonsUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setAssetPositionsRequestModel)
  }
);}





export const getGroupSetPositonsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupSetPositons>>, TError,{id: number;data?: SetAssetPositionsRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof groupSetPositons>>, TError,{id: number;data?: SetAssetPositionsRequestModel}, TContext> => {

const mutationKey = ['groupSetPositons'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof groupSetPositons>>, {id: number;data?: SetAssetPositionsRequestModel}> = (props) => {
          const {id,data} = props ?? {};

          return  groupSetPositons(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GroupSetPositonsMutationResult = NonNullable<Awaited<ReturnType<typeof groupSetPositons>>>
    export type GroupSetPositonsMutationBody = SetAssetPositionsRequestModel | undefined
    export type GroupSetPositonsMutationError = ProblemDetails

    export const useGroupSetPositons = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupSetPositons>>, TError,{id: number;data?: SetAssetPositionsRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof groupSetPositons>>,
        TError,
        {id: number;data?: SetAssetPositionsRequestModel},
        TContext
      > => {
      return useMutation(getGroupSetPositonsMutationOptions(options), queryClient);
    }
    export const getGroupSetCoverUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Groups/${id}/cover`
}

export const groupSetCover = async (id: number,
    setGroupCoverRequestModel?: SetGroupCoverRequestModel, options?: Parameters<typeof customClient>[1]): Promise<void> => {

  return customClient<void>(getGroupSetCoverUrl(id),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(setGroupCoverRequestModel)
  }
);}





export const getGroupSetCoverMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupSetCover>>, TError,{id: number;data?: SetGroupCoverRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof groupSetCover>>, TError,{id: number;data?: SetGroupCoverRequestModel}, TContext> => {

const mutationKey = ['groupSetCover'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof groupSetCover>>, {id: number;data?: SetGroupCoverRequestModel}> = (props) => {
          const {id,data} = props ?? {};

          return  groupSetCover(id,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GroupSetCoverMutationResult = NonNullable<Awaited<ReturnType<typeof groupSetCover>>>
    export type GroupSetCoverMutationBody = SetGroupCoverRequestModel | undefined
    export type GroupSetCoverMutationError = ProblemDetails

    export const useGroupSetCover = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupSetCover>>, TError,{id: number;data?: SetGroupCoverRequestModel}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof groupSetCover>>,
        TError,
        {id: number;data?: SetGroupCoverRequestModel},
        TContext
      > => {
      return useMutation(getGroupSetCoverMutationOptions(options), queryClient);
    }
