/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssetGroupResponseModel
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGroupDetailsUrl = (id: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Groups/${id}`
}

export const groupDetails = async (id: number, options?: Parameters<typeof customClient>[1]): Promise<AssetGroupResponseModel> => {

  return customClient<AssetGroupResponseModel>(getGroupDetailsUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGroupDetailsQueryKey = (id: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Groups/${id}`
    ] as const;
    }


export const getGroupDetailsQueryOptions = <TData = Awaited<ReturnType<typeof groupDetails>>, TError = unknown>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGroupDetailsQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof groupDetails>>> = ({ signal }) => groupDetails(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GroupDetailsQueryResult = NonNullable<Awaited<ReturnType<typeof groupDetails>>>
export type GroupDetailsQueryError = unknown


export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = unknown>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupDetails>>,
          TError,
          Awaited<ReturnType<typeof groupDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupDetails>>,
          TError,
          Awaited<ReturnType<typeof groupDetails>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGroupDetails<TData = Awaited<ReturnType<typeof groupDetails>>, TError = unknown>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupDetails>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGroupDetailsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






