/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer | v1
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssetTagsResponseModel,
  ProblemDetails
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type assetTagsResponse201 = {
  data: AssetTagsResponseModel
  status: 201
}

export type assetTagsResponse404 = {
  data: ProblemDetails
  status: 404
}

export type assetTagsResponseSuccess = (assetTagsResponse201) & {
  headers: Headers;
};
export type assetTagsResponseError = (assetTagsResponse404) & {
  headers: Headers;
};

export type assetTagsResponse = (assetTagsResponseSuccess | assetTagsResponseError)

export const getAssetTagsUrl = (assetId: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
}

export const assetTags = async (assetId: number | string, options?: RequestInit): Promise<assetTagsResponse> => {

  const res = await fetch(getAssetTagsUrl(assetId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: assetTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as assetTagsResponse
}





export const getAssetTagsQueryKey = (assetId: number | string,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
    ] as const;
    }


export const getAssetTagsQueryOptions = <TData = Awaited<ReturnType<typeof assetTags>>, TError = ProblemDetails>(assetId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetTagsQueryKey(assetId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetTags>>> = ({ signal }) => assetTags(assetId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: assetId !== null && assetId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetTagsQueryResult = NonNullable<Awaited<ReturnType<typeof assetTags>>>
export type AssetTagsQueryError = ProblemDetails


export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = ProblemDetails>(
 assetId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetTags>>,
          TError,
          Awaited<ReturnType<typeof assetTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = ProblemDetails>(
 assetId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetTags>>,
          TError,
          Awaited<ReturnType<typeof assetTags>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = ProblemDetails>(
 assetId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = ProblemDetails>(
 assetId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetTagsQueryOptions(assetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type addAssetTagsResponse404 = {
  data: ProblemDetails
  status: 404
}

;
export type addAssetTagsResponseError = (addAssetTagsResponse404) & {
  headers: Headers;
};

export type addAssetTagsResponse = (addAssetTagsResponseError)

export const getAddAssetTagsUrl = (assetId: number | string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
}

export const addAssetTags = async (assetId: number | string,
    addAssetTagsBody: string[], options?: RequestInit): Promise<addAssetTagsResponse> => {

  const res = await fetch(getAddAssetTagsUrl(assetId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addAssetTagsBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: addAssetTagsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as addAssetTagsResponse
}





export const getAddAssetTagsMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number | string;data: string[]}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number | string;data: string[]}, TContext> => {

const mutationKey = ['addAssetTags'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAssetTags>>, {assetId: number | string;data: string[]}> = (props) => {
          const {assetId,data} = props ?? {};

          return  addAssetTags(assetId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddAssetTagsMutationResult = NonNullable<Awaited<ReturnType<typeof addAssetTags>>>
    export type AddAssetTagsMutationBody = string[]
    export type AddAssetTagsMutationError = ProblemDetails

    export const useAddAssetTags = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number | string;data: string[]}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAssetTags>>,
        TError,
        {assetId: number | string;data: string[]},
        TContext
      > => {
      return useMutation(getAddAssetTagsMutationOptions(options), queryClient);
    }
    export type removeAssetTagResponse404 = {
  data: ProblemDetails
  status: 404
}

;
export type removeAssetTagResponseError = (removeAssetTagResponse404) & {
  headers: Headers;
};

export type removeAssetTagResponse = (removeAssetTagResponseError)

export const getRemoveAssetTagUrl = (assetId: number | string,
    tag: string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags/${tag}`
}

export const removeAssetTag = async (assetId: number | string,
    tag: string, options?: RequestInit): Promise<removeAssetTagResponse> => {

  const res = await fetch(getRemoveAssetTagUrl(assetId,tag),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: removeAssetTagResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as removeAssetTagResponse
}





export const getRemoveAssetTagMutationOptions = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number | string;tag: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number | string;tag: string}, TContext> => {

const mutationKey = ['removeAssetTag'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeAssetTag>>, {assetId: number | string;tag: string}> = (props) => {
          const {assetId,tag} = props ?? {};

          return  removeAssetTag(assetId,tag,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveAssetTagMutationResult = NonNullable<Awaited<ReturnType<typeof removeAssetTag>>>

    export type RemoveAssetTagMutationError = ProblemDetails

    export const useRemoveAssetTag = <TError = ProblemDetails,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number | string;tag: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeAssetTag>>,
        TError,
        {assetId: number | string;tag: string},
        TContext
      > => {
      return useMutation(getRemoveAssetTagMutationOptions(options), queryClient);
    }
