/**
 * Generated by orval 🍺
 * Do not edit manually.
 * GalleryViewer
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AssetGroupPositionResponseModel,
  AssetTagsResponseModel,
  NotFoundResult
} from '../model';

import { customClient } from '../../client/customClient';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getAssetInfoUrl = (assetId: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}`
}

export const assetInfo = async (assetId: number, options?: Parameters<typeof customClient>[1]): Promise<AssetGroupPositionResponseModel> => {

  return customClient<AssetGroupPositionResponseModel>(getAssetInfoUrl(assetId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAssetInfoQueryKey = (assetId: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}`
    ] as const;
    }


export const getAssetInfoQueryOptions = <TData = Awaited<ReturnType<typeof assetInfo>>, TError = NotFoundResult>(assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetInfoQueryKey(assetId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetInfo>>> = ({ signal }) => assetInfo(assetId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: assetId !== null && assetId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof assetInfo>>>
export type AssetInfoQueryError = NotFoundResult


export function useAssetInfo<TData = Awaited<ReturnType<typeof assetInfo>>, TError = NotFoundResult>(
 assetId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetInfo>>,
          TError,
          Awaited<ReturnType<typeof assetInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetInfo<TData = Awaited<ReturnType<typeof assetInfo>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetInfo>>,
          TError,
          Awaited<ReturnType<typeof assetInfo>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetInfo<TData = Awaited<ReturnType<typeof assetInfo>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetInfo<TData = Awaited<ReturnType<typeof assetInfo>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetInfo>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetInfoQueryOptions(assetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getAssetTagsUrl = (assetId: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
}

export const assetTags = async (assetId: number, options?: Parameters<typeof customClient>[1]): Promise<AssetTagsResponseModel> => {

  return customClient<AssetTagsResponseModel>(getAssetTagsUrl(assetId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getAssetTagsQueryKey = (assetId: number,) => {
    return [
    `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
    ] as const;
    }


export const getAssetTagsQueryOptions = <TData = Awaited<ReturnType<typeof assetTags>>, TError = NotFoundResult>(assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAssetTagsQueryKey(assetId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof assetTags>>> = ({ signal }) => assetTags(assetId, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: assetId !== null && assetId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AssetTagsQueryResult = NonNullable<Awaited<ReturnType<typeof assetTags>>>
export type AssetTagsQueryError = NotFoundResult


export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = NotFoundResult>(
 assetId: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetTags>>,
          TError,
          Awaited<ReturnType<typeof assetTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof assetTags>>,
          TError,
          Awaited<ReturnType<typeof assetTags>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAssetTags<TData = Awaited<ReturnType<typeof assetTags>>, TError = NotFoundResult>(
 assetId: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof assetTags>>, TError, TData>>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAssetTagsQueryOptions(assetId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export const getAddAssetTagsUrl = (assetId: number,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags`
}

export const addAssetTags = async (assetId: number,
    addAssetTagsBody?: string[], options?: Parameters<typeof customClient>[1]): Promise<void> => {

  return customClient<void>(getAddAssetTagsUrl(assetId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(addAssetTagsBody)
  }
);}





export const getAddAssetTagsMutationOptions = <TError = NotFoundResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number;data?: string[]}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number;data?: string[]}, TContext> => {

const mutationKey = ['addAssetTags'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addAssetTags>>, {assetId: number;data?: string[]}> = (props) => {
          const {assetId,data} = props ?? {};

          return  addAssetTags(assetId,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AddAssetTagsMutationResult = NonNullable<Awaited<ReturnType<typeof addAssetTags>>>
    export type AddAssetTagsMutationBody = string[] | undefined
    export type AddAssetTagsMutationError = NotFoundResult

    export const useAddAssetTags = <TError = NotFoundResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addAssetTags>>, TError,{assetId: number;data?: string[]}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addAssetTags>>,
        TError,
        {assetId: number;data?: string[]},
        TContext
      > => {
      return useMutation(getAddAssetTagsMutationOptions(options), queryClient);
    }
    export const getRemoveAssetTagUrl = (assetId: number,
    tag: string,) => {




  return `${import.meta.env.VITE_API_URL}/api/Assets/${assetId}/tags/${tag}`
}

export const removeAssetTag = async (assetId: number,
    tag: string, options?: Parameters<typeof customClient>[1]): Promise<void> => {

  return customClient<void>(getRemoveAssetTagUrl(assetId,tag),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getRemoveAssetTagMutationOptions = <TError = NotFoundResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number;tag: string}, TContext>, request?: SecondParameter<typeof customClient>}
): UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number;tag: string}, TContext> => {

const mutationKey = ['removeAssetTag'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeAssetTag>>, {assetId: number;tag: string}> = (props) => {
          const {assetId,tag} = props ?? {};

          return  removeAssetTag(assetId,tag,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RemoveAssetTagMutationResult = NonNullable<Awaited<ReturnType<typeof removeAssetTag>>>

    export type RemoveAssetTagMutationError = NotFoundResult

    export const useRemoveAssetTag = <TError = NotFoundResult,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeAssetTag>>, TError,{assetId: number;tag: string}, TContext>, request?: SecondParameter<typeof customClient>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeAssetTag>>,
        TError,
        {assetId: number;tag: string},
        TContext
      > => {
      return useMutation(getRemoveAssetTagMutationOptions(options), queryClient);
    }
